### ISSUE TITLE
tqdm vertical white space

### ISSUE THREAD

**Issue by stas00** [fastai/fastai_v1#17]
Is it just on my setup, or do you also get this strange vertical white space when tqdm is used? e.g. in `dev_nb/001b_fit.ipynb`

![snap](https://user-images.githubusercontent.com/10676103/44072987-82e7a4f8-9f46-11e8-9df4-72d39232cced.png)

it looks like it spits out a whole new notebook entry for each output, so that causes a weird vertical white space (as if there are two \n\n in between).

```
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=0, max=79), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 0.2706044764518738\n"
     ]
    },
```

**Comment by sgugger** [comment]
This is an issue that's supposed to be resolved on ipywidget side, but I have the same problem. Normally, the new outputs with a model_id that's set to '' shouldn't be displayed but we got this annoying vertical space.
Not sure what can be done about it...

**Comment by stas00** [comment]
Much better. Here is a snapshot:

![snap](https://user-images.githubusercontent.com/10676103/44119421-fd6ee15a-9fcd-11e8-8145-81f612c9eaf3.png)

Looks good to me.
