### ISSUE TITLE
fit_one_cycle parameters in wrong order in 007_wikitext_2

### ISSUE THREAD

**Issue by gsgbills** [fastai/fastai_v1#36]
It is 
fit_one_cycle(learn, 5e-3, 1, (0.8,0.7), wd=1.2e-6)
should be
fit_one_cycle(learn, cyc_len=1, max_lr=5e-3, moms=(0.8,0.7), wd=1.2e-6)

**Comment by sgugger** [comment]
Fixed in [this commit](https://github.com/fastai/fastai_v1/commit/ea529247230f3ddd44579103f949fa9797ed3ba1). Thanks for pointing it out!
