### ISSUE TITLE
rules is not defined in 007b_imdb_classifier

### ISSUE THREAD

**Issue by gsgbills** [fastai/fastai_v1#39]
----> 1 tokenizer = Tokenizer(rules=rules, special_cases=[BOS, FLD, UNK, PAD])
      2 bs,bptt = 50,70
      3 data = data_from_textcsv(LM_PATH, tokenizer, data_func=lm_data, max_vocab=60000, bs=bs, bptt=bptt)

NameError: name 'rules' is not defined

Solution: Replace rules by default_rules:
tokenizer = Tokenizer(rules=default_rules, special_cases=[BOS, FLD, UNK, PAD])

**Comment by sgugger** [comment]
Should be fixed by [this commit](https://github.com/fastai/fastai_v1/commit/bca16db09f44abb8b38f418ef739aa91e5eea595). Thanks for flagging!
