### ISSUE TITLE
Typos in 007b_...    qrnn;bool  should be qrnn:bool

### ISSUE THREAD

**Issue by gsgbills** [fastai/fastai_v1#42]
qrnn;bool  should be qrnn:bool
srt should be str
missing comma in: learn.fit_one_cycle(10, 1e-3, moms=(0.8,0.7), wd=0.03, pct_start=0.25)

**Comment by sgugger** [comment]
Fixed in [this](https://github.com/fastai/fastai_v1/commit/37cd054057450be32a2f57c3c1ea8afa7b103b6c).
